In [1]:
from IOU_computations import *
import cv2
from numpy import newaxis

In [2]:
path='MODEL_TF_SPACENET/TEST_SAVE/'
pred_path=path+'epoch_39_Predictions_26.jpg'
gt_path=path+'epoch_39_Groundtruth_26.jpg'

pred=cv2.imread(pred_path,cv2.IMREAD_GRAYSCALE)[newaxis,:,:]
gt=cv2.imread(gt_path,cv2.IMREAD_GRAYSCALE)[newaxis,:,:]
print(np.unique(pred))




[ 30 215]


In [3]:
iou_acc,f1,ious=predict_score_batch('iou_tmp/',gt,pred)

Image 0: 6 predictions proposed and 7 groundtruth
96.0
Polygone
45.0
549.0
77.0
486.0
1554.0
620.0
11069.0
[0.38235294 0.         0.         0.         0.         0.
 0.00513144]
[0. 0. 0. 0. 0. 0. 0.]
493.0
Polygone
45.0
549.0
77.0
486.0
1554.0
620.0
11069.0
[0.         0.         0.         0.89361702 0.         0.
 0.00268841]
[0.         0.         0.         0.89361702 0.         0.
 0.        ]
index 3
new size groundtruth 6
1.0
Polygone
45.0
549.0
77.0
1554.0
620.0
11069.0
[0.        0.        0.        0.0006435 0.        0.       ]
[0. 0. 0. 0. 0. 0.]
609.0
Polygone
45.0
549.0
77.0
1554.0
620.0
11069.0
[0.         0.         0.         0.         0.89076923 0.00257555]
[0.         0.         0.         0.         0.89076923 0.        ]
index 4
new size groundtruth 5
1531.0
Polygone
45.0
549.0
77.0
1554.0
11069.0
[0.         0.         0.         0.86856451 0.00775814]
[0.         0.         0.         0.86856451 0.        ]
index 3
new size groundtruth 4
11670.0
Polygone
45.0


In [4]:
print(iou_acc)
print(f1)
print(ious)


57.14285714285714
61.53846153846154
0.5094575366746878


In [10]:
from dataset_generator import DatasetGenerator

/home/s161362/.conda/envs/env_dhi/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [14]:
root_folder = '/scratch/SPACENET_DATA_PROCESSED/DATASET/120_x_120_8_bands_pansh/'

val_generator = DatasetGenerator.from_root_folder(root_folder+'VALIDATION/', batch_size=2)
val_generator=val_generator.shuffled()
val_generator=val_generator.__iter__()
X_val,Y_val=val_generator.__next__()
print(np.amax(Y_val))


1.0
